version: "3.8"
services:
  react:
    container_name: 'learn-climate-react-ui'
    build:
      context: ./learn-climate
      dockerfile: Dockerfile
    depends_on:
      - node
    ports:
      - '3000:3000'
  node:
    container_name: 'learn-climate-api'
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
  db:
    container_name: 'learn-climate-db'
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - './backend/database.env'
volumes:
  pgdata: {}
